name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
  
  workflow_dispatch:
    inputs:
      name:
        description: 'Github Actions'
        required: true
        default: 'Github Actions'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Packages
      run: apt install libelf-dev pkg-config
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
       version: "14"
    - name: Build Cargo-BPF
      run: cargo install cargo-bpf --git https://github.com/foniod/redbpf.git

