name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
  
  workflow_dispatch:
    inputs:
      name:
        description: 'Github Actions'
        required: true
        default: 'Github Actions'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Remove Latest Rust
      run: rustup self uninstall -y
    - name: Install Packages
      run: sudo apt install libelf-dev pkg-config -qy
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
       version: "14"
    - name: Install Rust 1.56
      run: rustup install 1.56
    - name: Build Cargo-BPF
      run: cargo install cargo-bpf --git https://github.com/foniod/redbpf.git
    - name: Build CS-FW
      run: |
        cd probes
        cargo build
        cargo bpf build --target-dir=../target

